### ISSUE TITLE
Backward compatibility of agp function 

### ISSUE THREAD

**Issue by anupamsingh81** [irinagain/iglu#86] opened 2021-07-04 13:03 UTC
agp function, works properly in rendering t1 object, Only on using strings as factors=FALSE , on systems with R 3.6 (probably changed with R 4.0). At least this is the case with my system

  # Calculate metrics
  tableStat = data.frame("Glucose statistics", "Value")

**Comment by irinagain** [comment] 2021-07-15 19:44
thank you for your comment, sorry it took us longer to get back to you as I was on a break. Can you please provide a reproducible example you used? e.g. which particular script did you run that give errors? a simple fix is to modify our R requirements in Description (currently it's >=3.1.0), but it would be most helpful if we can reproduce exactly for backward compatibility. Thank you!

**Comment by irinagain** [comment] 2021-08-13 15:49
Sine there appears to be no issue on later R versions and we can't reproduce, I am closing this. Feel free to reopen with example if you encounter any other issues. Thank you.

**Closed as completed by irinagain** 2021-08-13 15:49 UTC
